# Generated by Django 5.1.4 on 2024-12-06 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_tag_alter_post_options_remove_post_image_filter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='https://res.cloudinary.com/dsplumfvt/image/upload/green-apple_iubz3m', null=True, upload_to='posts/'),
        ),
    ]
