# Generated by Django 5.1.4 on 2024-12-06 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='green-apple_iubz3m', null=True, upload_to='posts/'),
        ),
    ]
