# Generated by Django 5.1.3 on 2024-11-29 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
