# Generated by Django 5.1.4 on 2024-12-05 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='../green-apple_kupzt9', upload_to='images/'),
        ),
    ]
